### ISSUE TITLE
VS Error CS0246 "Type or namespace could not be found" for ForgeNetworkingUnityEditor

### ISSUE THREAD

**Issue by KirkStallings** [BeardedManStudios/ForgeNetworkingRemastered#109]
### Version Number and Operating System(s):
Windows 10
Unity 2017.1.2
Visual Studio Community 2017.
Commit 8a441f3

### Expected behavior:
Open FNR in Visual Studio and build. Open project in Unity to resolve errors.

### Actual behavior:
Two of the reference paths do not get set correctly even after opening in Unity. Both of these are in the ForgeNetworkingUnityEditor references. Specifically they are UnityEditor and UnityEngine. This causes the namespace not to be recognized for the ForgeNetworkingUnityEditor code causing numerous CS0246 Visual Studio errors.

### Steps to reproduce:
Open the solution in Visual Studio. Build. Open project in Unity. Errors persist for ForgeNetworkingUnityEditor.

The workaround is to manually drag those two references from Windows File Explorer onto the references in Visual Studio.

The problem appears to have been caused by commit e9044f83c6448d6d1d0bfef7d764ef202720bed6 when Kallex pushed a commit. His csproj file had a different path for these two references. He would not have experienced the bug but other users with different environments would have encountered it.

The fix is probably to standardize the reference paths between the working Unity and broken UnityEditor references.

#### [Optional] Discord Username:
Kirk #5910

![unknown](https://user-images.githubusercontent.com/32686049/31471542-565d66c8-aeb7-11e7-8293-55d5a2993171.png)

**Comment by KirkStallings** [comment]
The problem is shown in the install video here:
https://youtu.be/Rtx7dCtspV4?t=385

**Comment by KirkStallings** [comment]
[Bug Notes.txt](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/files/1384328/Bug.Notes.txt)

**Comment by Crazy8ball** [comment]
Good catch, will be fixed on latest.
